server {
    listen 80;
    server_name wontia.com www.wontia.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name wontia.com www.wontia.com;
    ssl_certificate /etc/letsencrypt/live/wontia.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/wontia.com/privkey.pem;

    client_max_body_size 10M;
    proxy_read_timeout 600s;

    gzip on;
    gzip_vary on;
    gzip_min_length 1000;
    gzip_types text/css text/javascript application/javascript application/json image/svg+xml;
    gzip_comp_level 6;

    location /ice-api/ {
        proxy_pass http://127.0.0.1:3003/v1/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        add_header Access-Control-Allow-Origin "*" always;
    }

    location /assets/ {
        proxy_pass http://127.0.0.1:4003;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location / {
        proxy_pass http://127.0.0.1:4003;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }
}
