-- WWI Templates — 20 plantillas por sector (tenant 5). Cada preset define secciones (widgets)
-- del tema default + color de marca. TIA las usa como base al generar sitios.

INSERT IGNORE INTO wwi_templates (site_id, category_id, slug, name_es, name_en, description_es, description_en, preset, status, sort_order) VALUES
(5, (SELECT id FROM wwi_template_categories WHERE site_id=5 AND slug='restaurants'), 'tpl-restaurante', 'Restaurante Clasico', 'Classic Restaurant', 'Menu, galeria y reservas.', 'Menu, gallery and bookings.', '{"color":"#C2410C","sections":[{"widget":"hero","title":"Nuestro restaurante"},{"widget":"features","title":"Menu"},{"widget":"trust","title":"Testimonios"},{"widget":"cta","title":"Reservas"}]}', 'active', 1),
(5, (SELECT id FROM wwi_template_categories WHERE site_id=5 AND slug='legal'), 'tpl-abogados', 'Bufete Profesional', 'Professional Law Firm', 'Areas de practica y consultas.', 'Practice areas and consultations.', '{"color":"#1E3A8A","sections":[{"widget":"hero","title":"Asesoria legal"},{"widget":"features","title":"Areas de practica"},{"widget":"trust","title":"Casos y clientes"},{"widget":"cta","title":"Agenda una consulta"}]}', 'active', 1),
(5, (SELECT id FROM wwi_template_categories WHERE site_id=5 AND slug='medical'), 'tpl-medico', 'Consultorio Medico', 'Medical Practice', 'Servicios, equipo y citas.', 'Services, team and appointments.', '{"color":"#0F766E","sections":[{"widget":"hero","title":"Tu salud primero"},{"widget":"features","title":"Servicios"},{"widget":"howitworks","title":"Agenda tu cita"},{"widget":"cta","title":"Contacto"}]}', 'active', 1),
(5, (SELECT id FROM wwi_template_categories WHERE site_id=5 AND slug='real-estate'), 'tpl-inmobiliaria', 'Inmobiliaria Premium', 'Premium Real Estate', 'Propiedades destacadas.', 'Featured properties.', '{"color":"#374151","sections":[{"widget":"hero","title":"Tu proximo hogar"},{"widget":"features","title":"Propiedades"},{"widget":"trust","title":"Clientes felices"},{"widget":"cta","title":"Agenda visita"}]}', 'active', 1),
(5, (SELECT id FROM wwi_template_categories WHERE site_id=5 AND slug='construction'), 'tpl-construccion', 'Constructora Solida', 'Construction Firm', 'Proyectos y experiencia.', 'Projects and experience.', '{"color":"#B45309","sections":[{"widget":"hero","title":"Construimos contigo"},{"widget":"features","title":"Servicios"},{"widget":"howitworks","title":"Proceso"},{"widget":"cta","title":"Cotiza tu proyecto"}]}', 'active', 1),
(5, (SELECT id FROM wwi_template_categories WHERE site_id=5 AND slug='tourism'), 'tpl-turismo', 'Hotel & Turismo', 'Hotel & Tourism', 'Habitaciones y experiencias.', 'Rooms and experiences.', '{"color":"#0E7490","sections":[{"widget":"hero","title":"Descansa con nosotros"},{"widget":"features","title":"Habitaciones"},{"widget":"trust","title":"Huespedes"},{"widget":"cta","title":"Reserva ahora"}]}', 'active', 1),
(5, (SELECT id FROM wwi_template_categories WHERE site_id=5 AND slug='transport'), 'tpl-transporte', 'Transporte y Logistica', 'Transport & Logistics', 'Flota y cobertura.', 'Fleet and coverage.', '{"color":"#1F2937","sections":[{"widget":"hero","title":"Tu carga en movimiento"},{"widget":"features","title":"Servicios"},{"widget":"howitworks","title":"Como trabajamos"},{"widget":"cta","title":"Cotiza un envio"}]}', 'active', 1),
(5, (SELECT id FROM wwi_template_categories WHERE site_id=5 AND slug='beauty'), 'tpl-belleza', 'Belleza & Barberia', 'Beauty & Barbershop', 'Servicios y horarios.', 'Services and hours.', '{"color":"#BE185D","sections":[{"widget":"hero","title":"Tu estilo, nuestra pasion"},{"widget":"features","title":"Servicios"},{"widget":"trust","title":"Clientes"},{"widget":"cta","title":"Agenda tu cita"}]}', 'active', 1),
(5, (SELECT id FROM wwi_template_categories WHERE site_id=5 AND slug='fitness'), 'tpl-gimnasio', 'Gimnasio Energia', 'Fitness Center', 'Planes y entrenadores.', 'Plans and trainers.', '{"color":"#15803D","sections":[{"widget":"hero","title":"Entrena sin limites"},{"widget":"features","title":"Clases"},{"widget":"pricing","title":"Planes"},{"widget":"cta","title":"Empieza hoy"}]}', 'active', 1),
(5, (SELECT id FROM wwi_template_categories WHERE site_id=5 AND slug='education'), 'tpl-educacion', 'Centro Educativo', 'Education Center', 'Programas y admisiones.', 'Programs and admissions.', '{"color":"#4338CA","sections":[{"widget":"hero","title":"Educacion que transforma"},{"widget":"features","title":"Programas"},{"widget":"trust","title":"Comunidad"},{"widget":"cta","title":"Inscripciones"}]}', 'active', 1),
(5, (SELECT id FROM wwi_template_categories WHERE site_id=5 AND slug='consulting'), 'tpl-consultoria', 'Consultoria Estrategica', 'Strategic Consulting', 'Servicios y metodologia.', 'Services and methodology.', '{"color":"#334155","sections":[{"widget":"hero","title":"Resultados medibles"},{"widget":"features","title":"Servicios"},{"widget":"howitworks","title":"Metodologia"},{"widget":"cta","title":"Agenda diagnostico"}]}', 'active', 1),
(5, (SELECT id FROM wwi_template_categories WHERE site_id=5 AND slug='agencies'), 'tpl-agencia', 'Agencia y BPO', 'Agency & BPO', 'Servicios y equipo.', 'Services and team.', '{"color":"#6D28D9","sections":[{"widget":"hero","title":"Tu socio operativo"},{"widget":"features","title":"Servicios"},{"widget":"trust","title":"Clientes"},{"widget":"cta","title":"Hablemos"}]}', 'active', 1),
(5, (SELECT id FROM wwi_template_categories WHERE site_id=5 AND slug='tech'), 'tpl-tecnologia', 'Tecnologia y Software', 'Tech & Software', 'Productos y soporte.', 'Products and support.', '{"color":"#0369A1","sections":[{"widget":"hero","title":"Software que resuelve"},{"widget":"features","title":"Productos"},{"widget":"howitworks","title":"Integracion"},{"widget":"cta","title":"Solicita demo"}]}', 'active', 1),
(5, (SELECT id FROM wwi_template_categories WHERE site_id=5 AND slug='retail'), 'tpl-comercio', 'Tienda Local', 'Local Store', 'Productos destacados.', 'Featured products.', '{"color":"#B91C1C","sections":[{"widget":"hero","title":"Todo para ti"},{"widget":"features","title":"Categorias"},{"widget":"pricing","title":"Ofertas"},{"widget":"cta","title":"Visitanos"}]}', 'active', 1),
(5, (SELECT id FROM wwi_template_categories WHERE site_id=5 AND slug='automotive'), 'tpl-taller', 'Taller Automotriz', 'Auto Workshop', 'Servicios y garantia.', 'Services and warranty.', '{"color":"#92400E","sections":[{"widget":"hero","title":"Tu carro en buenas manos"},{"widget":"features","title":"Servicios"},{"widget":"trust","title":"Garantia"},{"widget":"cta","title":"Agenda revision"}]}', 'active', 1),
(5, (SELECT id FROM wwi_template_categories WHERE site_id=5 AND slug='fashion'), 'tpl-moda', 'Moda y Estilo', 'Fashion & Style', 'Colecciones.', 'Collections.', '{"color":"#9D174D","sections":[{"widget":"hero","title":"Nueva coleccion"},{"widget":"features","title":"Categorias"},{"widget":"trust","title":"Comunidad"},{"widget":"cta","title":"Compra ahora"}]}', 'active', 1),
(5, (SELECT id FROM wwi_template_categories WHERE site_id=5 AND slug='agriculture'), 'tpl-agro', 'Agroindustria', 'Agro Business', 'Productos del campo.', 'Farm products.', '{"color":"#3F6212","sections":[{"widget":"hero","title":"Del campo a tu mesa"},{"widget":"features","title":"Productos"},{"widget":"howitworks","title":"Proceso"},{"widget":"cta","title":"Contactanos"}]}', 'active', 1),
(5, (SELECT id FROM wwi_template_categories WHERE site_id=5 AND slug='pets'), 'tpl-veterinaria', 'Veterinaria & Mascotas', 'Vets & Pets', 'Servicios y cuidados.', 'Services and care.', '{"color":"#065F46","sections":[{"widget":"hero","title":"Cuidamos a tu mejor amigo"},{"widget":"features","title":"Servicios"},{"widget":"trust","title":"Familias felices"},{"widget":"cta","title":"Agenda cita"}]}', 'active', 1),
(5, (SELECT id FROM wwi_template_categories WHERE site_id=5 AND slug='events'), 'tpl-eventos', 'Eventos y Bodas', 'Events & Weddings', 'Planes y cobertura.', 'Plans and coverage.', '{"color":"#9A3412","sections":[{"widget":"hero","title":"Tu evento inolvidable"},{"widget":"features","title":"Servicios"},{"widget":"pricing","title":"Planes"},{"widget":"cta","title":"Cotiza tu evento"}]}', 'active', 1),
(5, (SELECT id FROM wwi_template_categories WHERE site_id=5 AND slug='cafes'), 'tpl-cafeteria', 'Cafeteria & Panaderia', 'Cafe & Bakery', 'Productos del dia.', 'Daily products.', '{"color":"#7C2D12","sections":[{"widget":"hero","title":"Recien hecho cada dia"},{"widget":"features","title":"Nuestro menu"},{"widget":"trust","title":"Clientes"},{"widget":"cta","title":"Visitanos"}]}', 'active', 1);
